version: '3.8'

networks:
  multicast_net:
    driver: bridge

services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=Node1
    networks:
      - multicast_net

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_ID=Node2
    networks:
      - multicast_net
