version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=node1
    networks:
      node_network:
        ipv4_address: 192.168.1.2

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_ID=node2
    networks:
      node_network:
        ipv4_address: 192.168.1.3

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_ID=node3
    networks:
      node_network:
        ipv4_address: 192.168.1.4

networks:
  node_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
