# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\x0b\x64istributed\" \n\x08NodeInfo\x12\x14\n\x0cnode_address\x18\x01 \x01(\t\"\xbc\x01\n\x14RegistrationResponse\x12\x15\n\rassigned_role\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tall_nodes\x18\x03 \x03(\t\x12;\n\x05roles\x18\x04 \x03(\x0b\x32,.distributed.RegistrationResponse.RolesEntry\x1a,\n\nRolesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"k\n\tRolesInfo\x12\x30\n\x05roles\x18\x01 \x03(\x0b\x32!.distributed.RolesInfo.RolesEntry\x1a,\n\nRolesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\x0bLineRequest\x12\x0c\n\x04line\x18\x01 \x01(\t\"\x8a\x01\n\x0c\x43ountRequest\x12\x14\n\x0cnode_address\x18\x01 \x01(\t\x12\x35\n\x06\x63ounts\x18\x02 \x03(\x0b\x32%.distributed.CountRequest.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x02\n\x0bNodeService\x12\x44\n\x08Register\x12\x15.distributed.NodeInfo\x1a!.distributed.RegistrationResponse\x12:\n\x0e\x42roadcastRoles\x12\x16.distributed.RolesInfo\x1a\x10.distributed.Ack\x12\x39\n\x0bProcessLine\x12\x18.distributed.LineRequest\x1a\x10.distributed.Ack\x12\x38\n\tSendCount\x12\x19.distributed.CountRequest\x1a\x10.distributed.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONRESPONSE_ROLESENTRY']._loaded_options = None
  _globals['_REGISTRATIONRESPONSE_ROLESENTRY']._serialized_options = b'8\001'
  _globals['_ROLESINFO_ROLESENTRY']._loaded_options = None
  _globals['_ROLESINFO_ROLESENTRY']._serialized_options = b'8\001'
  _globals['_COUNTREQUEST_COUNTSENTRY']._loaded_options = None
  _globals['_COUNTREQUEST_COUNTSENTRY']._serialized_options = b'8\001'
  _globals['_NODEINFO']._serialized_start=27
  _globals['_NODEINFO']._serialized_end=59
  _globals['_REGISTRATIONRESPONSE']._serialized_start=62
  _globals['_REGISTRATIONRESPONSE']._serialized_end=250
  _globals['_REGISTRATIONRESPONSE_ROLESENTRY']._serialized_start=206
  _globals['_REGISTRATIONRESPONSE_ROLESENTRY']._serialized_end=250
  _globals['_ROLESINFO']._serialized_start=252
  _globals['_ROLESINFO']._serialized_end=359
  _globals['_ROLESINFO_ROLESENTRY']._serialized_start=206
  _globals['_ROLESINFO_ROLESENTRY']._serialized_end=250
  _globals['_LINEREQUEST']._serialized_start=361
  _globals['_LINEREQUEST']._serialized_end=388
  _globals['_COUNTREQUEST']._serialized_start=391
  _globals['_COUNTREQUEST']._serialized_end=529
  _globals['_COUNTREQUEST_COUNTSENTRY']._serialized_start=484
  _globals['_COUNTREQUEST_COUNTSENTRY']._serialized_end=529
  _globals['_ACK']._serialized_start=531
  _globals['_ACK']._serialized_end=570
  _globals['_NODESERVICE']._serialized_start=573
  _globals['_NODESERVICE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
